version: '3.8'

services:
  mediamtx:
    build: ./mediamtx
    container_name: mediamtx-server
    ports:
      - "8554:8554"    # RTSP port
      - "8888:8888"    # HLS port
      - "8889:8889"    # WebRTC port
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
      - ./config:/config
    restart: unless-stopped
    networks:
      - camera-network

  web-server:
    image: nginx:alpine
    container_name: camera-web-server
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mediamtx
    restart: unless-stopped
    networks:
      - camera-network

networks:
  camera-network:
    driver: bridge